### ISSUE TITLE
Increase the size of the nodes in the node-pools in prod

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-iac#29]
Nodes where the api live need more RAM and probably more CPU. We need to check the needs. And also consider scaling on demand

**Comment by JacqueGM** [comment]
@llunaCreixent  is this necessary still -  I would say let's close this and add maybe a ticket to review together with Jon current infrastructure and improve/automate wherever is necessary :)

**Comment by JacqueGM** [comment]
is this necessary @llunaCreixent  I would like to change it to review capacity with Jon and see how to move forward?

**Comment by llunaCreixent** [comment]
I believe we concluded it was ok with the current resources. Anyway we can check the load in DO.

**Comment by JacqueGM** [comment]
Closed since at the moment, and for the last 14 days values are normal.
